-- SQL код для создания таблиц;

CREATE DATABASE library_db;

CREATE TABLE person (
                        person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL
);

CREATE TABLE book (
                      book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL,
                      issued_at TIMESTAMP
);

CREATE TABLE person_account
(
    id        int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username  varchar(100) NOT NULL UNIQUE,
    password  varchar(100) NOT NULL,
    email     varchar(100) NOT NULL UNIQUE,
    person_id int UNIQUE REFERENCES person (person_id) ON DELETE CASCADE
);